<?php
/**
 * Created by PhpStorm.
 * User: zhanghongbo
 * Date: 2020-07-15
 * Time: 16:22
 */
namespace backend\Modules\Orders;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'backend\Modules\Orders\Controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->viewPath = '@backend/Modules/Orders/Views';
    }
}