<?php
/**
 * Created by PhpStorm.
 * User: zhanghongbo
 * Date: 2020-07-31
 * Time: 14:32
 */
namespace Service\ServiceModules\ServiceMenu\Models;

use Service\ServiceModules\ServiceMenu\Models\Ar\MenuAr;

/**
 * Class MenuModel
 * @package Service\ServiceModules\ServiceMenu\Models
 */
class MenuModel extends MenuAr
{
    /**
     * @return array|false
     */
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|\console\models\MenuAr[]|\Service\Ars\Tables\ConfigTable[]|MenuAr[]|MenuModel[]|\yii\db\ActiveRecord[]
     */
    public function getTopMenu()
    {
        return self::find()->topTag()->orderBy('order asc')->all();
    }

}