<?php
/**
 * Created by PhpStorm.
 * User: zhanghongbo
 * Date: 2020-08-05
 * Time: 12:13
 */
namespace Service\ServiceModules\ServiceCustomer\Models;

use Service\Ars\Tables\CustomerCommonTable;
use Service\Ars\Tables\CustomerTable;

class CustomerModel extends CustomerTable
{

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }


    /**
     * Gets query for [[Customer]].
     *
     * @return \yii\db\ActiveQuery|\Service\Ars\Querys\CustomerQuery
     */
    public function getCustomerCommon()
    {
        return $this->hasOne(CustomerCommonModel::className(), ['customer_id' => 'id']);
//        return $this->hasOne(CustomerCommonModel::className(),['customer_id','id']);
    }

    /**
     * Gets query for [[CustomerCommons]].
     *
     * @return \yii\db\ActiveQuery|\Service\Ars\Querys\CustomerCommonQuery
     */
    public function getCustomerCommons()
    {
        return $this->hasOne(CustomerCommonTable::className(), ['customer_id' => 'id']);
    }

}