-- MySQL Script generated by MySQL Workbench
-- Mon Jul 27 17:03:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dengbei
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dengbei
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dengbei` DEFAULT CHARACTER SET utf8 ;
USE `dengbei` ;

-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer_role` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL COMMENT '客户认证，权限，角色表',
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `role` INT(10) NOT NULL,
  `parent_level_1` INT(10) UNSIGNED NULL DEFAULT 0,
  `parent_level_2` INT(10) UNSIGNED NULL DEFAULT 0,
  `return_money_ratio` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '返现比率(百分比)',
  `last_login_at` INT UNSIGNED NULL DEFAULT 0,
  `on_line` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `access_token` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `upated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_id` (`id` ASC),
  INDEX `idx_role` (`role` ASC),
  INDEX `parent_level_1` (`parent_level_1` ASC),
  INDEX `parent_level_2` (`parent_level_2` ASC),
  UNIQUE INDEX `access_token_UNIQUE` (`access_token` ASC),
  CONSTRAINT `fk_role_id_customer`
    FOREIGN KEY (`id`)
    REFERENCES `dengbei`.`sd_customer_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer_wx`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer_wx` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(10) UNSIGNED NOT NULL COMMENT '客户微信信息表',
  `nickname` VARCHAR(45) NOT NULL,
  `wx_openid` VARCHAR(45) NOT NULL,
  `xcx_openid` VARCHAR(45) NULL,
  `unionId` VARCHAR(45) NOT NULL,
  `avatar_url` VARCHAR(255) NULL,
  `gender` TINYINT(1) NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `mobile` VARCHAR(20) NULL,
  `watermark` VARCHAR(255) NULL COMMENT '用户认证信息',
  `is_wx_subscribe` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `wx_subscribe_time` INT(11) NULL DEFAULT 0,
  `created_at` INT(11) NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `wx_openid`, `unionId`),
  INDEX `idx.customer_id` (`customer_id` ASC),
  CONSTRAINT `fk_customer_id_wx`
    FOREIGN KEY (`id`)
    REFERENCES `dengbei`.`sd_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer_common`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer_common` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(10) NOT NULL COMMENT '客户副表',
  `service_id` INT(10) NULL,
  `order_buy_money` DECIMAL(10,2) NOT NULL,
  `order_refund_money` DECIMAL(10,2) NULL,
  `order_count` INT(5) NULL,
  `this_month_buymoney` DECIMAL(10,2) NULL,
  `last_month_buymoney` DECIMAL(10,2) NULL,
  `three_month_buymoney` DECIMAL(10,2) NULL,
  `is_three_money_buy` DECIMAL(10,2) NULL,
  `is_three_month_notbuy` DECIMAL(10,2) NULL,
  `is_year_buy` TINYINT(1) NULL,
  `status` TINYINT(1) NULL,
  `last_login_time` INT(11) NULL,
  `last_buy_time` INT(11) NULL,
  `is_address_trransfer` TINYINT(1) NULL,
  `is_store` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_id_common`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dengbei`.`sd_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer_return_money`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer_return_money` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `parent_level_1` INT(10) UNSIGNED NULL DEFAULT 0,
  `parent_level_2` INT(10) UNSIGNED NULL DEFAULT 0,
  `parent_level_3` INT(10) UNSIGNED NULL DEFAULT 0,
  `parent_1_ratio` DECIMAL(3,2) UNSIGNED NULL DEFAULT 0,
  `parent_2_ratio` DECIMAL(3,2) UNSIGNED NULL DEFAULT 0,
  `parent_3_ratio` DECIMAL(3,2) UNSIGNED NULL DEFAULT 0,
  `parent_1_return_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `parent_2_return_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `parent_3_return_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `sub_order_id` INT(10) UNSIGNED NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `return_time` INT(10) NOT NULL DEFAULT 0,
  `return_type` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `level_1_rely_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `level_2_rely_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `level_3_rely_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `order_role` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_id_return_money`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dengbei`.`sd_customer` (`parent_level_1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengbei`.`sd_constant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_constant` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(45) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dengbei`.`sd_open_role_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_open_role_relation` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `role_id` INT(10) NOT NULL,
  `limit_date_constant_id` INT(10) UNSIGNED NOT NULL,
  `limit_money_constant_id` INT(10) UNSIGNED NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `idx_role_id` (`role_id` ASC),
  CONSTRAINT `fk_role_id_relation`
    FOREIGN KEY (`id`)
    REFERENCES `dengbei`.`sd_customer_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
