-- MySQL Script generated by MySQL Workbench
-- Wed Aug 12 16:55:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dengbei
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dengbei
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dengbei` DEFAULT CHARACTER SET utf8 ;
USE `dengbei` ;

-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer_role` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色自增id',
  `name` VARCHAR(45) NOT NULL COMMENT '角色名称',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '角色值',
  PRIMARY KEY (`id`) COMMENT '角色表')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增编号',
  `c_id` INT UNSIGNED NOT NULL COMMENT '旧表did',
  `is_auth` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否认证(1:是,0:否)',
  `user_name` VARCHAR(45) NOT NULL COMMENT '名称',
  `password` VARCHAR(45) NOT NULL COMMENT '账户密码',
  `email` VARCHAR(45) NULL COMMENT '邮件',
  `balance` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT '余额',
  `role` INT(10) UNSIGNED NOT NULL COMMENT '角色id值',
  `parent_level_1` INT(10) UNSIGNED NULL DEFAULT 0 COMMENT '上级id值',
  `parent_level_2` INT(10) UNSIGNED NULL DEFAULT 0 COMMENT '上上级id值',
  `return_money_ratio` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '返现比率(百分比)',
  `on_line` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否在线(0:不在线，1:在线)',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态（1:可用，0:禁用）',
  `access_token` VARCHAR(100) NOT NULL COMMENT '用户请求身份标示',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建时间',
  `upated_at` INT UNSIGNED NULL DEFAULT 0 COMMENT '最后一次更新时间',
  PRIMARY KEY (`id`) COMMENT '客户主表',
  INDEX `idx_id` (`id` ASC),
  INDEX `idx_role` (`role` ASC),
  INDEX `idx_parent_level_1` (`parent_level_1` ASC),
  INDEX `idx_parent_level_2` (`parent_level_2` ASC),
  INDEX `idx_access_token` (`access_token` ASC),
  INDEX `idx_c_id` (`c_id` ASC),
  CONSTRAINT `fk_role_id_customer`
    FOREIGN KEY (`role`)
    REFERENCES `dengbei`.`sd_customer_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '客户主表';


-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer_wx`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer_wx` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `customer_id` INT(10) UNSIGNED NOT NULL COMMENT '关联客户id',
  `nickname` VARCHAR(45) NOT NULL COMMENT '昵称',
  `wx_openid` VARCHAR(45) NOT NULL COMMENT '微信-openid',
  `xcx_openid` VARCHAR(45) NULL COMMENT '小程序-openid',
  `unionId` VARCHAR(45) NOT NULL COMMENT '通用（微信-小程序）id',
  `avatar_url` VARCHAR(255) NULL COMMENT '头像地址',
  `gender` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '性别',
  `province` VARCHAR(45) NULL DEFAULT 0 COMMENT '省份id',
  `city` VARCHAR(45) NULL DEFAULT 0 COMMENT '城市id',
  `mobile` VARCHAR(20) NULL DEFAULT 0 COMMENT '授权电话',
  `watermark` VARCHAR(255) NULL COMMENT '用户认证信息',
  `is_wx_subscribe` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否关注公众号',
  `wx_subscribe_time` INT(11) NULL DEFAULT 0 COMMENT '公众号关注时间',
  `created_at` INT(11) NOT NULL DEFAULT 0 COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) COMMENT '客户微信表',
  INDEX `idx.customer_id` (`customer_id` ASC),
  CONSTRAINT `fk_customer_id_wx`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dengbei`.`sd_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '客户微信信息表';


-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer_common`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer_common` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '客户副表自增id',
  `customer_id` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联主表id',
  `service_id` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '客服id',
  `order_buy_money` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '购买订单总金额',
  `order_refund_money` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '退款总金额',
  `order_count` INT(5) UNSIGNED NOT NULL DEFAULT 0 COMMENT '下单量',
  `this_month_buymoney` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '本月购买金额',
  `last_month_buymoney` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '上个月购买金额',
  `three_month_buymoney` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '近三个月购买金额',
  `is_three_money_buy` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '三个月是否有购买（1:是，0:否）',
  `is_year_buy` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '近一年是否有购买(1:是，0:否)',
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '副表状态(1:可用0:禁用)',
  `last_login_time` INT(11) NOT NULL DEFAULT 0 COMMENT '最后登录时间',
  `last_buy_time` INT(11) NOT NULL DEFAULT 0 COMMENT '最后购买时间',
  `is_address_transfer` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '地址是否转发',
  `is_store` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否开灯店(1:是,0:否)',
  PRIMARY KEY (`id`) COMMENT '客户副表',
  INDEX `fk_customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_id_common`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dengbei`.`sd_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '客户副表';


-- -----------------------------------------------------
-- Table `dengbei`.`sd_customer_return_money`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_customer_return_money` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `parent_level_1` INT(10) UNSIGNED NULL DEFAULT 0,
  `parent_level_2` INT(10) UNSIGNED NULL DEFAULT 0,
  `parent_level_3` INT(10) UNSIGNED NULL DEFAULT 0,
  `parent_1_ratio` DECIMAL(3,2) UNSIGNED NULL DEFAULT 0,
  `parent_2_ratio` DECIMAL(3,2) UNSIGNED NULL DEFAULT 0,
  `parent_3_ratio` DECIMAL(3,2) UNSIGNED NULL DEFAULT 0,
  `parent_1_return_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `parent_2_return_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `parent_3_return_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `order_id` INT(10) UNSIGNED NOT NULL,
  `sub_order_id` INT(10) UNSIGNED NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `return_time` INT(10) NOT NULL DEFAULT 0,
  `return_type` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  `level_1_rely_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `level_2_rely_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `level_3_rely_money` DECIMAL(10,2) UNSIGNED NULL DEFAULT 0,
  `order_role` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) COMMENT '返现记录表',
  INDEX `fk_customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_customer_id_return_money`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dengbei`.`sd_customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '返现记录表';


-- -----------------------------------------------------
-- Table `dengbei`.`sd_constant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dengbei`.`sd_constant` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '常量id自增编号',
  `key` VARCHAR(45) NOT NULL COMMENT '常量唯一标示',
  `value` VARCHAR(45) NOT NULL COMMENT '常量值',
  `desc` VARCHAR(45) NOT NULL COMMENT '常量功能描述',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '常量状态（1:可用，0:不可用）',
  PRIMARY KEY (`id`) COMMENT '常量表',
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '常量表，存放定义的系统常量';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
