<?php

namespace Service\Modules\User\Models\Querys;

use Service\Base\Constants\CustomerConstant;

/**
 * This is the ActiveQuery class for [[\Service\Ars\Tables\UserTable]].
 *
 * @see \Service\Ars\Tables\UserTable
 */
class UserQuery extends \Service\Ars\Querys\UserQuery
{
    /**
     * 关联表名
     * @var
     */
    public $tableName;

    /**
     * 重写处理数据
     *
     * {@inheritdoc}
     * @return \Service\Ars\Tables\UserTable[]|array
     */
    public function all($db = null)
    {
        return parent::all($db);
    }

    /**
     * 重写处理数据
     *
     * {@inheritdoc}
     * @return \Service\Ars\Tables\UserTable|array|null
     */
    public function one($db = null)
    {
        return parent::one($db);
    }

    /**
     * 默认条件
     *
     * @param $builder
     * @return \Service\Ars\Querys\UserQuery|\yii\db\Query
     */
    public function prepare($builder)
    {
        $this->andWhere([$this->tableName.".type" => CustomerConstant::USER_TYPE_SERVICE]);
        return parent::prepare($builder); // TODO: Change the autogenerated stub
    }

    /**
     * 用户名条件
     *
     * @param $username
     * @return $this
     */
    public function username($username)
    {
        if(!empty($username)){
            $this->andWhere(['username' => $username]);
        }
        return $this;
    }
}
