<?php

return [
    'blogs0' => [
        'title' => 'Voluptas ut quasi dicta',
        'content' => 'Alice, in a sorrowful tone; \'at least there\'s no use in saying anything more till the Pigeon the opportunity of adding, \'You\'re looking for eggs, I know is, something comes at me like that!\' He got.',
        'views' => 'Sage',
        'is_delete' => true,
        'created_at' => '1976-06-05',
        'updated_at' => '2000-08-22',
        'file' => 'https://lorempixel.com/640/480/?46467',
        'file2' => 'https://lorempixel.com/640/480/?33643',
    ],
    'blogs1' => [
        'title' => 'Eveniet iste voluptatem delectus dicta',
        'content' => 'Alice would not open any of them. However, on the spot.\' This did not venture to go on. \'And so these three little sisters--they were learning to draw,\' the Dormouse followed him: the March Hare.',
        'views' => 'Bradly',
        'is_delete' => true,
        'created_at' => '2012-06-26',
        'updated_at' => '1998-03-18',
        'file' => 'https://lorempixel.com/640/480/?55645',
        'file2' => 'https://lorempixel.com/640/480/?36785',
    ],
    'blogs2' => [
        'title' => 'Inventore ipsa alias voluptas aut',
        'content' => 'I know is, it would be only rustling in the last few minutes it puffed away without being invited,\' said the Queen, but she could guess, she was now the right distance--but then I wonder if I know I.',
        'views' => 'Astrid',
        'is_delete' => true,
        'created_at' => '1984-05-26',
        'updated_at' => '2016-12-31',
        'file' => 'https://lorempixel.com/640/480/?18965',
        'file2' => 'https://lorempixel.com/640/480/?58956',
    ],
    'blogs3' => [
        'title' => 'Sequi ea dolores facere et',
        'content' => 'YOU like cats if you were all locked; and when Alice had learnt several things of this sort of lullaby to it in the act of crawling away: besides all this, there was nothing so VERY tired of being.',
        'views' => 'Joseph',
        'is_delete' => false,
        'created_at' => '1973-10-18',
        'updated_at' => '1987-07-07',
        'file' => 'https://lorempixel.com/640/480/?91347',
        'file2' => 'https://lorempixel.com/640/480/?18314',
    ],
    'blogs4' => [
        'title' => 'Dolorem labore eveniet et quia odio',
        'content' => 'Alice. \'Nothing,\' said Alice. \'Of course they were\', said the cook. \'Treacle,\' said the Dodo, \'the best way to fly up into the wood. \'It\'s the oldest rule in the world am I? Ah, THAT\'S the great.',
        'views' => 'Sasha',
        'is_delete' => false,
        'created_at' => '2000-10-08',
        'updated_at' => '1998-06-21',
        'file' => 'https://lorempixel.com/640/480/?55348',
        'file2' => 'https://lorempixel.com/640/480/?94972',
    ],
    'blogs5' => [
        'title' => 'Impedit omnis atque ex earum non',
        'content' => 'Edwin and Morcar, the earls of Mercia and Northumbria, declared for him: and even Stigand, the patriotic archbishop of Canterbury, found it made Alice quite hungry to look over their shoulders, that.',
        'views' => 'Caroline',
        'is_delete' => true,
        'created_at' => '1984-06-11',
        'updated_at' => '1996-11-19',
        'file' => 'https://lorempixel.com/640/480/?22755',
        'file2' => 'https://lorempixel.com/640/480/?45213',
    ],
    'blogs6' => [
        'title' => 'Incidunt dicta laboriosam enim repudiandae ipsum',
        'content' => 'When I used to call him Tortoise, if he had to run back into the sky all the time it vanished quite slowly, beginning with the words came very queer indeed:-- \'\'Tis the voice of the officers: but.',
        'views' => 'Vidal',
        'is_delete' => true,
        'created_at' => '2008-01-20',
        'updated_at' => '1991-11-27',
        'file' => 'https://lorempixel.com/640/480/?31240',
        'file2' => 'https://lorempixel.com/640/480/?88329',
    ],
    'blogs7' => [
        'title' => 'Et necessitatibus iste voluptatem eaque quidem',
        'content' => 'Alice thought the whole she thought to herself, \'after such a thing as "I eat what I like"!\' \'You might just as she spoke. (The unfortunate little Bill had left off writing on his slate with one.',
        'views' => 'Cleora',
        'is_delete' => true,
        'created_at' => '1978-07-05',
        'updated_at' => '1992-10-15',
        'file' => 'https://lorempixel.com/640/480/?51105',
        'file2' => 'https://lorempixel.com/640/480/?42929',
    ],
    'blogs8' => [
        'title' => 'Aut qui aspernatur repudiandae alias',
        'content' => 'It doesn\'t look like it?\' he said, \'on and off, for days and days.\' \'But what am I to get very tired of swimming about here, O Mouse!\' (Alice thought this a very poor speaker,\' said the Mouse to.',
        'views' => 'Noble',
        'is_delete' => true,
        'created_at' => '1990-04-18',
        'updated_at' => '1987-05-21',
        'file' => 'https://lorempixel.com/640/480/?53530',
        'file2' => 'https://lorempixel.com/640/480/?94638',
    ],
    'blogs9' => [
        'title' => 'Ut ex earum voluptatum consequatur mollitia',
        'content' => 'Hatter. He had been looking at them with one foot. \'Get up!\' said the Duck: \'it\'s generally a ridge or furrow in the middle of the evening, beautiful Soup! Beau--ootiful Soo--oop! Beau--ootiful.',
        'views' => 'Orval',
        'is_delete' => true,
        'created_at' => '1973-11-13',
        'updated_at' => '1992-03-03',
        'file' => 'https://lorempixel.com/640/480/?82474',
        'file2' => 'https://lorempixel.com/640/480/?82058',
    ],
];
