<?php

return [
    'User0' => [
        'username' => 'Adipisci sit placeat quas a',
        'password' => 'I would talk on such a thing as a boon, Was kindly permitted to pocket the spoon: While the Owl had the best of educations--in fact, we went to the confused clamour of the song, she kept fanning.',
        'auth_key' => 'Mallie',
        'password_hash' => true,
        'password_reset_token' => '1993-01-10',
        'email' => '1974-10-22',
        'status' => 'https://lorempixel.com/640/480/?16465',
        'created_at' => 'https://lorempixel.com/640/480/?98004',
        'updated_at' => 'https://lorempixel.com/640/480/?58249',
    ],
    'User1' => [
        'username' => 'Molestias vero consequuntur quod',
        'password' => 'Alice for protection. \'You shan\'t be able! I shall think nothing of the bread-and-butter. Just at this corner--No, tie \'em together first--they don\'t reach half high enough yet--Oh! they\'ll do next!.',
        'auth_key' => 'Efren',
        'password_hash' => true,
        'password_reset_token' => '2010-06-20',
        'email' => '1987-05-23',
        'status' => 'https://lorempixel.com/640/480/?99685',
        'created_at' => 'https://lorempixel.com/640/480/?21228',
        'updated_at' => 'https://lorempixel.com/640/480/?70993',
    ],
    'User2' => [
        'username' => 'Provident provident ad natus fugit ipsam',
        'password' => 'Dodo, \'the best way to change the subject of conversation. While she was appealed to by the soldiers, who of course you know I\'m mad?\' said Alice. The King turned pale, and shut his note-book.',
        'auth_key' => 'Noble',
        'password_hash' => true,
        'password_reset_token' => '1989-01-27',
        'email' => '1993-02-28',
        'status' => 'https://lorempixel.com/640/480/?97973',
        'created_at' => 'https://lorempixel.com/640/480/?86603',
        'updated_at' => 'https://lorempixel.com/640/480/?91888',
    ],
    'User3' => [
        'username' => 'Quia qui eligendi esse',
        'password' => 'Five, \'and I\'ll tell you just now what the name of nearly everything there. \'That\'s the first to break the silence. \'What day of the shelves as she could not swim. He sent them word I had to sing.',
        'auth_key' => 'Randall',
        'password_hash' => false,
        'password_reset_token' => '1991-06-05',
        'email' => '2020-03-13',
        'status' => 'https://lorempixel.com/640/480/?30640',
        'created_at' => 'https://lorempixel.com/640/480/?65713',
        'updated_at' => 'https://lorempixel.com/640/480/?82801',
    ],
    'User4' => [
        'username' => 'Quidem dolor labore minus sit est libero',
        'password' => 'Alice very politely; but she knew that it was certainly English. \'I don\'t think they play at all fairly,\' Alice began, in rather a handsome pig, I think.\' And she opened it, and fortunately was just.',
        'auth_key' => 'Everardo',
        'password_hash' => false,
        'password_reset_token' => '2013-09-22',
        'email' => '1996-08-01',
        'status' => 'https://lorempixel.com/640/480/?82215',
        'created_at' => 'https://lorempixel.com/640/480/?87731',
        'updated_at' => 'https://lorempixel.com/640/480/?41452',
    ],
    'User5' => [
        'username' => 'Voluptates voluptatem repellat sit',
        'password' => 'Latitude or Longitude either, but thought they were all turning into little cakes as they used to come upon them THIS size: why, I should think!\' (Dinah was the only difficulty was, that you think I.',
        'auth_key' => 'Glennie',
        'password_hash' => true,
        'password_reset_token' => '1996-06-27',
        'email' => '1980-08-16',
        'status' => 'https://lorempixel.com/640/480/?69057',
        'created_at' => 'https://lorempixel.com/640/480/?70066',
        'updated_at' => 'https://lorempixel.com/640/480/?66970',
    ],
    'User6' => [
        'username' => 'Voluptas non est qui',
        'password' => 'CHAPTER X. The Lobster Quadrille is!\' \'No, indeed,\' said Alice. \'Why not?\' said the Duchess. \'I make you grow shorter.\' \'One side will make you grow taller, and the whole party swam to the law, And.',
        'auth_key' => 'Ola',
        'password_hash' => false,
        'password_reset_token' => '1986-04-14',
        'email' => '2020-04-06',
        'status' => 'https://lorempixel.com/640/480/?62489',
        'created_at' => 'https://lorempixel.com/640/480/?54154',
        'updated_at' => 'https://lorempixel.com/640/480/?28821',
    ],
    'User7' => [
        'username' => 'Tempora aliquid voluptas et',
        'password' => 'Alice. \'That\'s very curious.\' \'It\'s all about it!\' Last came a little girl or a serpent?\' \'It matters a good deal on where you want to be?\' it asked. \'Oh, I\'m not used to know. Let me see: four.',
        'auth_key' => 'Antwan',
        'password_hash' => true,
        'password_reset_token' => '1985-08-25',
        'email' => '2002-01-21',
        'status' => 'https://lorempixel.com/640/480/?24828',
        'created_at' => 'https://lorempixel.com/640/480/?66282',
        'updated_at' => 'https://lorempixel.com/640/480/?37971',
    ],
    'User8' => [
        'username' => 'Est adipisci quasi harum',
        'password' => 'I wish I hadn\'t mentioned Dinah!\' she said to the little crocodile Improve his shining tail, And pour the waters of the wood--(she considered him to you, Though they were trying which word sounded.',
        'auth_key' => 'Tyrel',
        'password_hash' => false,
        'password_reset_token' => '1996-09-01',
        'email' => '2001-12-18',
        'status' => 'https://lorempixel.com/640/480/?85046',
        'created_at' => 'https://lorempixel.com/640/480/?98618',
        'updated_at' => 'https://lorempixel.com/640/480/?97473',
    ],
    'User9' => [
        'username' => 'Suscipit quam commodi illum error harum consequatur',
        'password' => 'Alice, rather alarmed at the other players, and shouting \'Off with his whiskers!\' For some minutes the whole window!\' \'Sure, it does, yer honour: but it\'s an arm for all that.\' \'Well, it\'s got no.',
        'auth_key' => 'Fanny',
        'password_hash' => true,
        'password_reset_token' => '2009-12-31',
        'email' => '2017-06-24',
        'status' => 'https://lorempixel.com/640/480/?62851',
        'created_at' => 'https://lorempixel.com/640/480/?11361',
        'updated_at' => 'https://lorempixel.com/640/480/?34926',
    ],
];
